
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.ArrayList;
import java.util.Base64;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.crypto.Cipher;
import javax.crypto.SecretKey;
import javax.crypto.SecretKeyFactory;
import javax.crypto.spec.DESedeKeySpec;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

public class Display extends javax.swing.JFrame {

    DefaultListModel listModel = new DefaultListModel ();
    static int userIndex;
    static ArrayList<User> arrUser;

    public Display (ArrayList<User> arrUser , int userIndex) {
        initComponents ();

        for ( int i = 1; i < arrUser.size (); i ++ ) {
            listModel.addElement (arrUser.get (i).getName () + " " + arrUser.get (i).getUserName ());
        }

        Display.arrUser = arrUser;
        Display.userIndex = userIndex;
        listUser.setModel (listModel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings ( "unchecked" )
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jScrollPane1 = new javax.swing.JScrollPane();
        listUser = new javax.swing.JList();
        btnDelete = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        listUser.setFont(new java.awt.Font("Tahoma", 1, 28)); // NOI18N
        jScrollPane1.setViewportView(listUser);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 110, 445, 284));

        btnDelete.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        getContentPane().add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 440, 126, 49));

        btnBack.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        getContentPane().add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 440, 121, 49));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        int op = JOptionPane.showConfirmDialog (listUser , "Do you really want to delete?" , "Delete" , JOptionPane.YES_NO_OPTION);

        int index = listUser.getSelectedIndex ();

        if ( op == JOptionPane.YES_OPTION ) {
            System.out.println ("op: " + op);
            listModel.removeElementAt (index);
            arrUser.remove (index + 1);
        }

        for ( int i = 0; i < arrUser.size (); i ++ ) {
            System.out.println ("display: " + arrUser.get (i).getName () + "," + arrUser.get (i).getUserName () + "," + arrUser.get (i).getPassword () + "," + arrUser.get (i).getRePassword () + "," + arrUser.get (i).getQuestion () + "," + arrUser.get (i).getAnswer ());

        }

        try {
            Register reg = new Register (arrUser);
            reg.saveToFile (arrUser);
        } catch ( Exception e ) {
            e.printStackTrace ();
        }


    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed

        AdminMenu um = new AdminMenu (arrUser , userIndex);
        um.setVisible (true);
        um.setSize (900 , 600);
        um.setDefaultCloseOperation (JFrame.EXIT_ON_CLOSE);
        this.dispose ();


    }//GEN-LAST:event_btnBackActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        /*
            Change File Permission
         */
        File shadow = new File ("shadow.txt");
        File integrity = new File ("integrity.txt");

        shadow.setExecutable (false);
        shadow.setReadable (false);
        shadow.setWritable (false);

        integrity.setExecutable (false);
        integrity.setReadable (false);
        integrity.setWritable (false);
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main (String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for ( javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels () ) {
                if ( "Nimbus".equals (info.getName ()) ) {
                    javax.swing.UIManager.setLookAndFeel (info.getClassName ());
                    break;

                }
            }
        } catch ( ClassNotFoundException ex ) {
            java.util.logging.Logger.getLogger (Display.class
                      .getName ()).log (java.util.logging.Level.SEVERE , null , ex);

        } catch ( InstantiationException ex ) {
            java.util.logging.Logger.getLogger (Display.class
                      .getName ()).log (java.util.logging.Level.SEVERE , null , ex);

        } catch ( IllegalAccessException ex ) {
            java.util.logging.Logger.getLogger (Display.class
                      .getName ()).log (java.util.logging.Level.SEVERE , null , ex);

        } catch ( javax.swing.UnsupportedLookAndFeelException ex ) {
            java.util.logging.Logger.getLogger (Display.class
                      .getName ()).log (java.util.logging.Level.SEVERE , null , ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater (new Runnable () {
            public void run () {
                new Display (arrUser , userIndex).setVisible (true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDelete;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList listUser;
    // End of variables declaration//GEN-END:variables
}
