
import java.io.File;
import java.io.FileNotFoundException;
import java.io.PrintWriter;
import java.security.NoSuchAlgorithmException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.crypto.NoSuchPaddingException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;


public class EditForm extends javax.swing.JFrame {

    public static ArrayList<User> arrUser;
    public static int adminIndex;
    boolean checkPassword = false;

    /**
     * Creates new form EditForm
     *
     * @param arrUser
     * @param adminIndex
     */
    public EditForm (ArrayList<User> arrUser , int adminIndex) {
        initComponents ();

        EditForm.arrUser = arrUser;
        EditForm.adminIndex = adminIndex;
//        for(int i= 0; i < arrUser.size(); i++){
//            System.out.println("Name: " + arrUser.get(i).getName());
//        }
        txtReTypePassword.setText (EditForm.arrUser.get (adminIndex).getRePassword ());
        txtUserName.setText (EditForm.arrUser.get (adminIndex).getUserName ());
        txtPassword.setText (EditForm.arrUser.get (adminIndex).getPassword ());
        txtName.setText (EditForm.arrUser.get (adminIndex).getName ());
    }

    public boolean isValidPassword (String strPass) {
        String num = ".*[0-9].*";
        String alpha = ".*[A-Z].*";
        return strPass.matches (num) && strPass.matches (alpha);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings ( "unchecked" )
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtName = new javax.swing.JTextField();
        txtUserName = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        txtReTypePassword = new javax.swing.JPasswordField();
        btnUpdate = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        cboxQuestion = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtAnswer = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtNameMouseClicked(evt);
            }
        });
        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });
        getContentPane().add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 64, 197, 40));

        txtUserName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtUserNameMouseClicked(evt);
            }
        });
        txtUserName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUserNameActionPerformed(evt);
            }
        });
        getContentPane().add(txtUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 123, 197, 40));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Name");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 70, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Username");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 130, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Password");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 200, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Re-type Password");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 270, -1, -1));

        txtPassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtPasswordMouseClicked(evt);
            }
        });
        txtPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPasswordActionPerformed(evt);
            }
        });
        getContentPane().add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 189, 197, 40));

        txtReTypePassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtReTypePasswordMouseClicked(evt);
            }
        });
        txtReTypePassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtReTypePasswordActionPerformed(evt);
            }
        });
        getContentPane().add(txtReTypePassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 260, 197, 40));

        btnUpdate.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        getContentPane().add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 460, 111, 44));

        btnBack.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        getContentPane().add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 460, 121, 44));

        cboxQuestion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Please Select...", "What's your birthplace?", "What's your favourite animal?", "What's your first school?" }));
        cboxQuestion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboxQuestionActionPerformed(evt);
            }
        });
        getContentPane().add(cboxQuestion, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 320, 200, 40));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Question");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 330, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Answer");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 390, -1, -1));

        txtAnswer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtAnswerMouseClicked(evt);
            }
        });
        getContentPane().add(txtAnswer, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 380, 200, 40));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed

    }//GEN-LAST:event_txtNameActionPerformed

    private void txtUserNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUserNameActionPerformed


    }//GEN-LAST:event_txtUserNameActionPerformed

    private void txtPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordActionPerformed

    }//GEN-LAST:event_txtPasswordActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed

        String username = txtUserName.getText ();
        String name = txtName.getText ();
        String password = txtPassword.getText ();
        String rePassword = txtReTypePassword.getText ();

        boolean userUpdate = false;
        boolean userCheck = false;
        boolean matchPassword = false;

        for ( int i = 0; i < arrUser.size (); i ++ ) {

            if ( username.equals (arrUser.get (i).getUserName ()) && i != 0 ) {
                JOptionPane.showMessageDialog (null , "This username already exists, please select another username" , "Error" , JOptionPane.ERROR_MESSAGE);
                userCheck = false;
                break;
            }

            if ( i == adminIndex ) {
                userUpdate = true;
            }

            if (  ! username.equals (arrUser.get (i).getUserName ()) ) {
                userCheck = true;
            }

        }

        checkPassword = isValidPassword (password);
        if (  ! ( password.equals (" ") ) &&  ! ( password.equals ("") ) ) {
            if (  ! checkPassword ) {

                JOptionPane.showMessageDialog (null , "Password Should Have Uppercase, Lowercase and Numbers" , "Error" , JOptionPane.ERROR_MESSAGE);

            } else {
                int length = password.length ();
                if ( length < 7 ) {
                    JOptionPane.showMessageDialog (null , "Password Should Be 8 Or More Characters" , "Error" , JOptionPane.ERROR_MESSAGE);
                } else {

                    if ( password.equals (rePassword) ) {
                        matchPassword = true;
                    } else {
                        matchPassword = false;
                        JOptionPane.showMessageDialog (null , "Password Mismatch" , "Error" , JOptionPane.ERROR_MESSAGE);
                    }
                }
            }
        }

        boolean isAnswer = false;
        boolean isQuestion = false;
        String question = ( String ) cboxQuestion.getSelectedItem ();
        String answer = txtAnswer.getText ();

        if ( cboxQuestion.getSelectedIndex () != 0 ) {
            question = ( String ) cboxQuestion.getSelectedItem ();
            isQuestion = true;
        } else {
            JOptionPane.showMessageDialog (null , "Please Select One Question" , "Select" , JOptionPane.ERROR_MESSAGE);
            isQuestion = false;
        }

        if ( answer.equals ("") ) {
            JOptionPane.showMessageDialog (null , "You can't leave the answer blank" , "Select" , JOptionPane.ERROR_MESSAGE);
            isAnswer = false;
        } else {
            isAnswer = true;
        }

        for ( int i = 0; i < arrUser.size (); i ++ ) {
            if ( i == adminIndex && userUpdate && userCheck && matchPassword && isQuestion && isAnswer ) {
                String hashPass = BCrypt.hashpw (password , BCrypt.gensalt (13));
                arrUser.set (adminIndex , new User (name , username , hashPass , hashPass , question , answer));
                try {
                    Register reg = new Register (arrUser);
                    reg.saveToFile (arrUser);
                } catch ( NoSuchAlgorithmException | NoSuchPaddingException ex ) {
                    Logger.getLogger (EditForm.class.getName ()).log (Level.SEVERE , null , ex);
                }
                JOptionPane.showMessageDialog (null , "Your account was successfully updated" , "Update Account" , JOptionPane.INFORMATION_MESSAGE);
                AdminMenu um = new AdminMenu (arrUser , adminIndex);
                um.setVisible (true);
                um.setSize (900 , 600);
                um.setDefaultCloseOperation (JFrame.EXIT_ON_CLOSE);
                this.dispose ();
            }
        }

    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed

        AdminMenu um = new AdminMenu (arrUser , adminIndex);
        um.setVisible (true);
        um.setSize (900 , 600);
        um.setDefaultCloseOperation (JFrame.EXIT_ON_CLOSE);
        this.dispose ();

    }//GEN-LAST:event_btnBackActionPerformed

    private void txtReTypePasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtReTypePasswordActionPerformed

    }//GEN-LAST:event_txtReTypePasswordActionPerformed

    private void cboxQuestionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboxQuestionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboxQuestionActionPerformed

    private void txtNameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNameMouseClicked
        txtName.setText ("");
    }//GEN-LAST:event_txtNameMouseClicked

    private void txtUserNameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtUserNameMouseClicked
        txtUserName.setText ("");
    }//GEN-LAST:event_txtUserNameMouseClicked

    private void txtPasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtPasswordMouseClicked
        txtPassword.setText ("");
    }//GEN-LAST:event_txtPasswordMouseClicked

    private void txtReTypePasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtReTypePasswordMouseClicked
        txtReTypePassword.setText ("");
    }//GEN-LAST:event_txtReTypePasswordMouseClicked

    private void txtAnswerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtAnswerMouseClicked
        txtAnswer.setText ("");
    }//GEN-LAST:event_txtAnswerMouseClicked

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        /*
            Change File Permission
         */
        File shadow = new File ("shadow.txt");
        File integrity = new File ("integrity.txt");

        shadow.setExecutable (false);
        shadow.setReadable (false);
        shadow.setWritable (false);

        integrity.setExecutable (false);
        integrity.setReadable (false);
        integrity.setWritable (false);
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main (String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for ( javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels () ) {
                if ( "Nimbus".equals (info.getName ()) ) {
                    javax.swing.UIManager.setLookAndFeel (info.getClassName ());
                    break;
                }
            }
        } catch ( ClassNotFoundException ex ) {
            java.util.logging.Logger.getLogger (EditForm.class.getName ()).log (java.util.logging.Level.SEVERE , null , ex);
        } catch ( InstantiationException ex ) {
            java.util.logging.Logger.getLogger (EditForm.class.getName ()).log (java.util.logging.Level.SEVERE , null , ex);
        } catch ( IllegalAccessException ex ) {
            java.util.logging.Logger.getLogger (EditForm.class.getName ()).log (java.util.logging.Level.SEVERE , null , ex);
        } catch ( javax.swing.UnsupportedLookAndFeelException ex ) {
            java.util.logging.Logger.getLogger (EditForm.class.getName ()).log (java.util.logging.Level.SEVERE , null , ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater (new Runnable () {
            public void run () {
                new EditForm (arrUser , adminIndex).setVisible (true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> cboxQuestion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField txtAnswer;
    private javax.swing.JTextField txtName;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JPasswordField txtReTypePassword;
    private javax.swing.JTextField txtUserName;
    // End of variables declaration//GEN-END:variables
}
